const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(value ?? 0);
const number = value => new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value ?? 0);

function drawChart(rows){const svg=document.querySelector('#chart');svg.innerHTML='<line class="chart-base" x1="0" y1="230" x2="1000" y2="230"/>';if(rows.length<2)return;const values=rows.map(row=>row.equity);const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((value,index)=>`${index/(values.length-1)*1000},${230-(value-min)/range*190}`).join(' ');svg.innerHTML+=`<polyline class="chart-line" points="${points}"/>`;}

function renderPositions(rows){const body=document.querySelector('#positions-body');document.querySelector('#position-count').textContent=`${rows.length} instruments`;body.innerHTML=rows.length?rows.map(row=>`<tr><td><b>${row.symbol}</b></td><td class="side-${row.side}">${row.side}</td><td>${money(row.notional)}</td><td>${number(row.entry_price)}</td><td>${number(row.mark_price)}</td><td class="${row.unrealized_pnl>=0?'positive':'negative'}">${money(row.unrealized_pnl)}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No positions yet.</td></tr>';}

function renderExecutions(rows){document.querySelector('#events').innerHTML=rows.length?rows.map(row=>`<li><b>${row.symbol}</b> ${row.side} ${row.filled_quantity?number(row.filled_quantity):''}<br><small>${row.status} · ${row.slippage_bps==null?'—':number(row.slippage_bps)+' bps'}</small></li>`).join(''):'<li class="empty">Waiting for the first daily rebalance.</li>';}

async function refresh(){try{const [session,positions,equity,executions]=await Promise.all(['/api/session','/api/positions','/api/equity','/api/executions'].map(url=>fetch(url).then(response=>{if(!response.ok)throw new Error(`${url} unavailable`);return response.json();})));const account=session.account;const replay=session.status==='historical_replay';document.querySelector('#status').textContent=session.status.replaceAll('_',' ').toUpperCase();document.querySelector('#mode-label').textContent=replay?'HISTORICAL OOS REPLAY':'LIVE PAPER SESSION';document.querySelector('#session-mode').innerHTML=replay?'REPLAY / LOCAL OHLCV<br><span>NO ORDER BOOK OR SLIPPAGE</span>':'PAPER / BYBIT LINEAR<br><span>1D CLOSE ONLY</span>';document.querySelector('#equity').textContent=money(account.equity);document.querySelector('#cash').textContent=money(account.cash);document.querySelector('#gross').textContent=money(account.gross_notional);document.querySelector('#cutoff').textContent=session.model.cutoff_date;document.querySelector('#last-date').textContent=session.last_decision_date||'Awaiting first close';document.querySelector('#model-info').textContent=`${session.model.backend.toUpperCase()} · h${session.model.horizon_days} · ${session.model.seed_count} seeds · cut-off ${session.model.cutoff_date}`;renderPositions(positions);renderExecutions(executions);drawChart(equity);}catch(error){document.querySelector('#status').textContent='API UNAVAILABLE';}}

refresh();
setInterval(refresh,3000);
